import {
  Alert,
  Box,
  Button,
  Card,
  Divider,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Stack,
  Typography,
} from '@mui/material';
import moment from 'moment';
import * as React from 'react';
import { toast } from 'react-toastify';

import apis from '@/api';
import type { AiConfig } from '@/api/live';
import type { PortfolioInsight } from '@/api/analytics';
import { Iconify } from '@/components/Iconify';

function Section({ title, icon, color, items }: { title: string; icon: string; color: string; items: string[] }) {
  if (!items.length) return null;
  return (
    <Box>
      <Stack direction="row" spacing={0.75} sx={{ alignItems: 'center', px: 2, pt: 1.5, pb: 0.5 }}>
        <Iconify icon={icon} width={15} sx={{ color }} />
        <Typography
          sx={{
            fontSize: '0.68rem',
            fontWeight: 700,
            color: 'text.secondary',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
          }}
        >
          {title}
        </Typography>
      </Stack>
      <List dense sx={{ py: 0, px: 1 }}>
        {items.map((item, i) => (
          <ListItem key={i} sx={{ py: 0.25, alignItems: 'flex-start' }}>
            <ListItemIcon sx={{ minWidth: 22, mt: 0.5 }}>
              <Box sx={{ width: 5, height: 5, borderRadius: '50%', bgcolor: color }} />
            </ListItemIcon>
            <ListItemText slotProps={{ primary: { sx: { fontSize: '0.82rem' } } }} primary={item} />
          </ListItem>
        ))}
      </List>
    </Box>
  );
}

export default function PortfolioInsightsCard() {
  const [aiConfig, setAiConfig] = React.useState<AiConfig | null>(null);
  const [insight, setInsight] = React.useState<PortfolioInsight | null>(null);
  const [loading, setLoading] = React.useState(false);

  React.useEffect(() => {
    apis.live
      .getAiConfig()
      .then(setAiConfig)
      .catch(() => {});
  }, []);

  const isOllama = aiConfig?.enabled && aiConfig.provider === 'ollama';

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await apis.analytics.getPortfolioInsights();
      setInsight(result);
    } catch (err: any) {
      toast.error(err.message || 'Failed to generate portfolio insights');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card variant="outlined">
      <Stack direction="row" sx={{ alignItems: 'center', px: 2, py: 1.25, gap: 1 }}>
        <Iconify icon="mdi:brain" width={16} sx={{ color: 'primary.main' }} />
        <Typography
          sx={{
            fontWeight: 700,
            fontSize: '0.72rem',
            color: 'text.secondary',
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
          }}
        >
          AI Portfolio Review
        </Typography>
        <Box sx={{ flexGrow: 1 }} />
        {isOllama && (
          <Button
            size="small"
            variant="contained"
            onClick={handleGenerate}
            disabled={loading}
            startIcon={<Iconify icon={loading ? 'mdi:loading' : 'mdi:auto-fix'} width={15} />}
            sx={{ fontSize: '0.75rem', textTransform: 'none' }}
          >
            {loading ? 'Analyzing…' : insight ? 'Regenerate' : 'Analyze'}
          </Button>
        )}
      </Stack>
      <Divider />

      <Box sx={{ p: 2 }}>
        <Alert severity="info" icon={<Iconify icon="mdi:shield-lock-outline" />} sx={{ fontSize: '0.78rem' }}>
          This is the only feature that analyzes your personal holdings with AI. To keep your financial data private, it
          runs <strong>only on a local Ollama model</strong> — your portfolio never leaves this machine.
        </Alert>
      </Box>

      {!isOllama ? (
        <Box sx={{ px: 2, pb: 2 }}>
          <Typography sx={{ fontSize: '0.82rem', color: 'text.disabled' }}>
            Set the AI provider to <strong>Ollama (Local)</strong> and enable the AI Agent in Settings to use portfolio
            analysis.
          </Typography>
        </Box>
      ) : (
        insight && (
          <>
            <Box sx={{ px: 2, pb: 1 }}>
              <Typography sx={{ fontSize: '0.88rem', lineHeight: 1.5 }}>{insight.summary}</Typography>
            </Box>
            <Section title="Observations" icon="mdi:eye-outline" color="#3b82f6" items={insight.observations} />
            <Section title="Risks" icon="mdi:alert-outline" color="var(--pd-down)" items={insight.risks} />
            <Section title="Suggestions" icon="mdi:lightbulb-outline" color="var(--pd-up)" items={insight.suggestions} />
            <Typography sx={{ fontSize: '0.68rem', color: 'text.disabled', px: 2, py: 1.25 }}>
              Generated by {insight.provider} ({insight.model}) {moment(insight.generatedAt).fromNow()}. Analysis only —
              not financial advice.
            </Typography>
          </>
        )
      )}
    </Card>
  );
}
