name: "Portfolio Dashboard"
description: "My first real add-on!"
version: "1.1.0"
slug: "portfolio-dashboard"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 3000