name: "Portflolio Dashboard"
description: "A dashboard to manage and track your stock movements!"
version: "1.0.5"
slug: "portfolio-dasboard"
init: false
stage: stable
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
webui: http://[HOST]:[PORT:3000]/dashboard
watchdog: http://[HOST]:[PORT:3000]/dashboard
ports:
  3000/tcp: 3000
options:
  DB_HOST: http://[HOST]:[PORT:3001]
schema:
  DB_HOST: str
panel_icon: mdi:chart-line-stacked