name: 'Portflolio Dashboard DB'
description: 'This acts as the backend database for portfolio dashboard!'
version: '1.0.6'
slug: 'portfolio-dasboard-db'
init: false
stage: stable
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
watchdog: http://[HOST]:[PORT:3001]/health
ports:
  3001/tcp: 3001
options:
  FINN_HUB_API: https://www.finnhub.io/api/v1
  FINN_HUB_API_KEY:
schema:
  FINN_HUB_API: str
  FINN_HUB_API_KEY: str
ingress: true
# panel_icon: mdi:puzzle
# panel_title: Defaults to the add-on name, but can be modified with this option.
